using System.Net;
using System.Text;
using Markdig.Extensions.Yaml;
using Markdig.Syntax;
using YamlDotNet.RepresentationModel;

namespace MdReader.Core;

/// <summary>
/// Extracts YAML front matter and renders it as a collapsed metadata card at the
/// top of the document — never dumped as text, never silently discarded.
/// </summary>
public static class FrontMatter
{
    /// <summary>
    /// Returns the metadata card HTML for the document's front matter, or an empty
    /// string when there is none. All values are HTML-encoded here; this output is
    /// generated by mdreader, not by the untrusted document renderer, but the
    /// values inside it are still untrusted text.
    /// </summary>
    public static string RenderCard(MarkdownDocument document, string markdown)
    {
        var block = document.Descendants<YamlFrontMatterBlock>().FirstOrDefault();
        if (block is null)
        {
            return string.Empty;
        }

        var yamlText = ExtractText(block, markdown);
        if (string.IsNullOrWhiteSpace(yamlText))
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.Append("<details class=\"front-matter\" data-source-line=\"1\">");
        sb.Append("<summary>Document metadata</summary>");

        try
        {
            var yaml = new YamlStream();
            yaml.Load(new StringReader(yamlText));

            if (yaml.Documents.Count > 0 && yaml.Documents[0].RootNode is YamlMappingNode mapping)
            {
                sb.Append("<table class=\"front-matter-table\">");
                foreach (var entry in mapping.Children)
                {
                    sb.Append("<tr><th>");
                    sb.Append(WebUtility.HtmlEncode(NodeToText(entry.Key)));
                    sb.Append("</th><td>");
                    sb.Append(WebUtility.HtmlEncode(NodeToText(entry.Value)));
                    sb.Append("</td></tr>");
                }

                sb.Append("</table>");
            }
            else
            {
                AppendRaw(sb, yamlText, error: null);
            }
        }
        catch (YamlDotNet.Core.YamlException ex)
        {
            // Malformed YAML still shows up — as raw text with an error note.
            AppendRaw(sb, yamlText, ex.Message);
        }

        sb.Append("</details>");
        return sb.ToString();
    }

    private static void AppendRaw(StringBuilder sb, string yamlText, string? error)
    {
        if (error is not null)
        {
            sb.Append("<p class=\"front-matter-error\">Front matter could not be parsed as YAML: ");
            sb.Append(WebUtility.HtmlEncode(error));
            sb.Append("</p>");
        }

        sb.Append("<pre class=\"front-matter-raw\"><code>");
        sb.Append(WebUtility.HtmlEncode(yamlText));
        sb.Append("</code></pre>");
    }

    private static string ExtractText(YamlFrontMatterBlock block, string markdown)
    {
        // block.Lines contains the YAML content without the --- fences.
        var sb = new StringBuilder();
        var lines = block.Lines.Lines;
        for (var i = 0; i < block.Lines.Count; i++)
        {
            sb.AppendLine(lines[i].Slice.ToString());
        }

        return sb.ToString();
    }

    private static string NodeToText(YamlNode node) => node switch
    {
        YamlScalarNode scalar => scalar.Value ?? string.Empty,
        YamlSequenceNode sequence => string.Join(", ", sequence.Children.Select(NodeToText)),
        YamlMappingNode mapping => string.Join("; ", mapping.Children.Select(kv => $"{NodeToText(kv.Key)}: {NodeToText(kv.Value)}")),
        _ => node.ToString() ?? string.Empty,
    };
}
